Script started on 2017年03月08日 (週三) 23時25分04秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m whoami; pwd
pd2vm
/home/pd2vm/lab1
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m  git config -l
user.email=yoyo908382gmail.com
user.name=yotashi
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/yotashi/first_repository.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m  git clone https://github.com/<your github account>/lab1.git
bash: your: No such file or directory
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m  git clone https://github.com/<your github account>/lab1.git[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gity/lab1.gito/lab1.gitt/lab1.gita/lab1.gits/lab1.gith/lab1.giti/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 10, done.[K
remote: Compressing objects:  16% (1/6)   [Kremote: Compressing objects:  33% (2/6)   [Kremote: Compressing objects:  50% (3/6)   [Kremote: Compressing objects:  66% (4/6)   [Kremote: Compressing objects:  83% (5/6)   [Kremote: Compressing objects: 100% (6/6)   [Kremote: Compressing objects: 100% (6/6), done.[K
remote: Total 10 (delta 0), reused 7 (delta 0), pack-reused 0[K
Unpacking objects:  10% (1/10)   Unpacking objects:  20% (2/10)   Unpacking objects:  30% (3/10)   Unpacking objects:  40% (4/10)   Unpacking objects:  50% (5/10)   Unpacking objects:  60% (6/10)   Unpacking objects:  70% (7/10)   Unpacking objects:  80% (8/10)   Unpacking objects:  90% (9/10)   Unpacking objects: 100% (10/10)   Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m exit

Script done on 2017年03月08日 (週三) 23時26分21秒
